import { SiteConfig } from "./siteConfig.mjs";

export const siteConfigs = {
	armyTech: new SiteConfig({
		store_name: "ArmyTech",
		store_id: "armytech",
		store_url: "https://www.armytech.com.ar",
		store_image: "/src/assets/stores/armytech.png",
		trust_factor_manual: 90,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "buenos aires", "buena_reputacion", "componentes"],
		pages: [
			"/371-pc-hogar-oficina",
			"/370-pc-gamer",
			"/494-pc-diseno",
			"/372-mini-pc",
			"/508-notebook-oficina",
			"/507-notebook-gamer",
			"/506-notebook-diseno",
		],
		selectors: {
			productWrapper: ".js-product-miniature-wrapper",
			title_raw: ".h3.product-title a",
			price: ".product-price",
			product_url: ".h3.product-title a",
			image_url: ".product-thumbnail img",
		},
		timeout: 30000,
	}),

	//
	venex: new SiteConfig({
		store_name: "Venex",
		store_id: "venex",
		store_url: "https://www.venex.com.ar",
		store_image: "/images/stores/venex.png",
		trust_factor_manual: 85,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "cordoba", "buena_reputacion", "componentes"],
		pages: [
			"/componentes-de-pc/discos-duros-mecanicos",
			"/componentes-de-pc/discos-solidos-ssd",
			"/componentes-de-pc/memorias-ram/desktop",
			"/componentes-de-pc/memorias-ram/notebook",
			"/componentes-de-pc/microprocesadores",
			"/componentes-de-pc/motherboards/amd",
			"/componentes-de-pc/motherboards/intel",
			"/componentes-de-pc/placas-de-video",
			"/componentes-de-pc/gabinetes",
			"/componentes-de-pc/refrigeracion/fan-coolers",
			"/componentes-de-pc/combos-de-actualizaciones",
			"/pc-de-escritorio/pcs-de-escritorio",
			"/sillas-gamerssillas-gamers/sillas-gamer",
			"/estabilizadores-ups-y-zapatillas",
		],
		selectors: {
			productWrapper: ".product-box",
			title_raw: ".product-box-title a",
			price: ".current-price",
			product_url: ".product-box-title a",
			image_url: ".thumb img",
			stock_raw: null, // no tiene info de stock, pero todos los productos que muestran están en stock
			installmentes: null, // no tienen info de cuotas por ahora
		},
		timeout: 30000,
	}),
	//
	//	maximus: new SiteConfig({
	//		name: "Maximus",
	//		siteImage: "/images/stores/maximus.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.maximus.com.ar",
	//		categories: ["/Productos/maximus.aspx?/CAT=-1/SCAT=-1/M=-1/BUS=*/OR=1"],
	//		selectors: {
	//			productWrapper: ".col-md-prod",
	//			title_raw: ".title-prod",
	//			image: ".image img",
	//		},
	//		pagination: {
	//			type: "replace",
	//			pattern: "PAGE=1",
	//			replacement: "PAGE={page}",
	//		},
	//		maxPages: 1,
	//	}),
	//	compraGamer: new SiteConfig({
	//		name: "CompraGamer",
	//		siteImage: "/images/stores/compragamer.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://compragamer.com/productos?",
	//		categories: [
	//			"cate=58",
	//			"cate=59",
	//			"cate=27",
	//			"cate=48",
	//			"cate=26",
	//			"cate=49",
	//			"cate=62",
	//			"cate=15",
	//			"cate=47",
	//			"cate=16",
	//			"cate=19",
	//			"cate=81",
	//			"cate=90",
	//			"cate=35",
	//			"cate=36",
	//			"cate=67",
	//			"cate=7",
	//			"cate=100",
	//			"cate=34",
	//			"cate=5",
	//			"cate=8",
	//			"cate=39",
	//			"cate=2",
	//			"cate=13",
	//			"cate=18",
	//			"cate=38",
	//			"cate=65",
	//			"cate=72",
	//			"cate=74",
	//			"cate=84",
	//			"cate=113",
	//			"cate=66",
	//			"cate=14",
	//			"cate=83",
	//			"cate=31",
	//			"cate=111",
	//			"cate=21",
	//			"cate=3",
	//			"cate=24",
	//		],
	//		selectors: {
	//			productWrapper: "cgw-product-card",
	//			title_raw: "h3.product-card__title",
	//			price: ".product-card__cart__price--current",
	//			product_url: "a",
	//			image: ".medium product-card__image img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "cate",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	ngTech: new SiteConfig({
	//		name: "NGTech",
	//		siteImage: "/images/stores/ngtech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.ngtechnologies.com.ar",
	//		categories: ["/search/?q=*"],
	//		selectors: {
	//			productWrapper: ".js-product-container",
	//			title_raw: ".js-item-name",
	//			price: ".js-price-display",
	//			product_url: "a",
	//			image: "img.js-product-item-image-private",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "mpage",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	mgmGamers: new SiteConfig({
	//		name: "MGM Gamers",
	//		siteImage: "/images/stores/mgmgamers.png",
	//		isPcComponent: false,
	//		isSetup: true,
	//		store_url: "https://mgmgamers.store",
	//		categories: ["/search/?q=*"],
	//		selectors: {
	//			productWrapper: ".js-item-product",
	//			title_raw: ".js-item-name",
	//			price: "[data-product-price]",
	//			product_url: ".item-link",
	//			image: ".js-item-image-padding img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "mpage",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	slotOne: new SiteConfig({
	//		name: "Slot-One",
	//		siteImage: "/images/stores/slotone.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.slot-one.com.ar",
	//		categories: ["/search/?q=*"],
	//		selectors: {
	//			productWrapper: ".js-product-container",
	//			title_raw: ".js-item-name",
	//			price: ".js-price-display",
	//			product_url: "a",
	//			image: "img.js-product-item-image-private",
	//		},
	//		isOutOfStock: (element) => element.textContent.includes("Sin stock"),
	//		pagination: {
	//			type: "queryParam",
	//			param: "mpage",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	puertoMinero: new SiteConfig({
	//		name: "Puerto Minero",
	//		siteImage: "/images/stores/puertominero.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.puertominero.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: ".product-card-one",
	//			title_raw: ".title",
	//			price: ".price",
	//			product_url: "a",
	//			image: "img",
	//		},
	//		isOutOfStock: (element) => element.textContent.includes("Agotado"),
	//		maxPages: 1,
	//	}),
	//	//
	//	tech710: new SiteConfig({
	//		name: "710Tech",
	//		siteImage: "/images/stores/710tech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.710tech.com.ar/",
	//		categories: [
	//			"accesorios/",
	//			"almacenamiento/",
	//			"combos/",
	//			"consolas/",
	//			"equipos/",
	//			"fuente/",
	//			"gabinetes/",
	//			"memoria-ram/",
	//			"monitores/",
	//			"motherboard/",
	//			"notebook/",
	//			"parlantes/",
	//			"perifericos-/",
	//			"placas-de-video/",
	//			"procesadores/",
	//			"refrigeracion-/",
	//		],
	//		selectors: {
	//			productWrapper: "div.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".price, .card-description",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	bytes37: new SiteConfig({
	//		name: "37 Bytes",
	//		siteImage: "/images/stores/37bytes.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.37bytes.com.ar/",
	//		categories: ["productos/"],
	//		selectors: {
	//			productWrapper: ".js-product-container",
	//			title_raw: ".js-item-name",
	//			price: ".js-price-display",
	//			product_url: "a",
	//			image: "img.js-product-item-image-private",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	dinobyte: new SiteConfig({
	//		name: "Dinobyte",
	//		siteImage: "/images/stores/dinobyte.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://dinobyte.ar/categoria-producto/",
	//		categories: ["hardware/", "equipos/", "monitores/", "perifericos/", "otros/", "consolas/"],
	//		selectors: {
	//			productWrapper: ".w-grid-item-h",
	//			title_raw: ".post_title",
	//			price: ".woocommerce-Price-amount",
	//			product_url: ".post_image a",
	//			image: ".wp-post-image",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//		isOutOfStock: (element) => element.textContent.includes("Sin stock"),
	//	}),
	//
	//	fullH4rd: new SiteConfig({
	//		name: "Full H4rd",
	//		siteImage: "/images/stores/fullh4rd.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://fullh4rd.com.ar/",
	//		categories: [
	//			"pcarmada",
	//			"tag/hardware",
	//			"tag/periferico",
	//			"cat/supra/32/notebooks/1",
	//			"cat/supra/18/monitores/1",
	//		],
	//		selectors: {
	//			productWrapper: ".item.product-list",
	//			title_raw: ".info h3",
	//			price: ".price",
	//			product_url: "a",
	//			image: ".image img",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "{page}",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	gnPoint: new SiteConfig({
	//		name: "GN Point",
	//		siteImage: "/images/stores/gnpoint.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://gnpoint.com.ar/productos/",
	//		categories: ["notebooks/", "productos/", "perifericos-de-pc/", "pc-de-escritorio/"],
	//		selectors: {
	//			productWrapper: ".product.type-product",
	//			title_raw: ".woocommerce-loop-product__title_ink",
	//			price: ".woocommerce-Price-amount bdi",
	//			product_url: ".woocommerce-loop-image-link",
	//			image: ".attachment-woocommerce_thumbnail.size-woocommerce_thumbnail",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	gamersPoint: new SiteConfig({
	//		name: "Gamers Point",
	//		siteImage: "/images/stores/gamerspoint.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.gamerspoint.com.ar/categoria/",
	//		categories: ["componentes-de-pc/", "perifericos/", "armados-pc/", "monitores/", "notebooks/"],
	//		selectors: {
	//			productWrapper: ".product.type-product",
	//			title_raw: ".woocommerce-loop-product__title",
	//			price: ".woocommerce-Price-amount bdi",
	//			product_url: ".post_image a",
	//			image: ".wp-post-image",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//		isOutOfStock: (element) => element.textContent.includes("Sin stock"),
	//	}),
	//
	//	GamingCity: new SiteConfig({
	//		//this has the ui of mercado libre, and the pages (1,2,3,4etc) are very, very weird
	//		name: "Gaming City",
	//		siteImage: "/images/stores/gamingcity.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.gamingcity.com.ar/",
	//		categories: [
	//			"/p/arma-tu-pc-landing",
	//			"/monitores",
	//			"/placa-de-video",
	//			"/procesadores",
	//			"/notebooks",
	//			"/_DisplayType_G_BRAND_16360",
	//			"/listado/computacion/",
	//			"/listado/consolas-videojuegos/",
	//			"/_BRAND_15788",
	//			"/_BRAND_7885",
	//			"/_BRAND_16360",
	//			"/_BRAND_47354",
	//			"/_BRAND_7294334",
	//			"/_BRAND_13180685",
	//			"/_BRAND_41874",
	//			"/_BRAND_448156",
	//			"/_BRAND_899182",
	//			"/_BRAND_2796190",
	//			"/_BRAND_195091",
	//			"/_BRAND_18685",
	//			"/_BRAND_15795",
	//			"/_BRAND_9597",
	//			"/_BRAND_9565",
	//			"/_BRAND_479",
	//			"/_BRAND_47687",
	//			"/_BRAND_2542655",
	//			"/_BRAND_2542653",
	//			"/_BRAND_17992",
	//			"/_BRAND_17265",
	//			"/_BRAND_6504514",
	//			"/_BRAND_2017",
	//			"/_BRAND_16244",
	//			"/_BRAND_1258105",
	//			"/_BRAND_9593",
	//			"/_BRAND_9079566",
	//			"/_BRAND_42328",
	//			"/_BRAND_41057",
	//			"/_BRAND_4060193",
	//			"/_BRAND_2301927",
	//			"/_BRAND_17337102",
	//			"/_BRAND_16739",
	//			"/_BRAND_15162008",
	//			"/_BRAND_995",
	//			"/_BRAND_9807",
	//			"/_BRAND_9344",
	//			"/_BRAND_8784",
	//			"/_BRAND_80801",
	//			"/_BRAND_5986",
	//			"/p/privacidad",
	//			"/p/contacto",
	//			"/gz/cart",
	//			"/nuestros-productos",
	//			"/outlet%20outlet",
	//			"/listado/computacion/laptops-accesorios/notebooks",
	//			"/listado/computacion/pc-escritorio",
	//			"/p/garantia",
	//			"/p/sucursales",
	//			"/p/como-comprar",
	//			"/listado/computacion/pc-escritorio/pc-escritorio",
	//			"/p/como-cancelar-compra",
	//			"/p/contratos-de-adhesion",
	//			"/p/quienes-somos",
	//			"/p/drivers",
	//			"/p/avisos-legales",
	//		],
	//		selectors: {
	//			productWrapper: ".mshops-search-polycard.poly-card",
	//			title_raw: ".poly-component__title",
	//			price: ".andes-money-amount__fraction",
	//			product_url: ".poly-component__title",
	//			image: ".poly-component__picture",
	//		},
	//		maxPages: 1,
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".poly-price__current"),
	//		maxPages: 1,
	//	}),
	//
	//	gezatek: new SiteConfig({
	//		name: "Gezatek",
	//		siteImage: "/images/stores/gezatek.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.gezatek.com.ar/tienda/",
	//		categories: [
	//			"pc-hogar-y-oficina/",
	//			"pc-basic-gamer/",
	//			"pc-elite-gamer/",
	//			"pc-xtreme-gamer/",
	//			"notebooks/",
	//			"accesorios-notebook/",
	//			"smart-tv/",
	//			"combos-amd/",
	//			"combos-intel/",
	//			"procesadores-amd//",
	//			"procesadores-intel/",
	//			"mothers-amd-am4/",
	//			"mothers-amd-am5/",
	//			"mothers-intel-lga1200/",
	//			"mothers-intel-lga1700/",
	//			"mothers-intel-lga1851/",
	//			"ram-ddr3/",
	//			"ram-ddr4/",
	//			"ram-ddr5/",
	//			"ram-sodimm-ddr4/",
	//			"vga-nvidia/",
	//			"vga-amd/",
	//			"monitores/",
	//			"discos-ssd-sata3/",
	//			"discos-ssd-m2-nvme/",
	//			"discos-rigidos/",
	//			"discos-externos-usb/",
	//			"opticos/",
	//			"fuentes/",
	//			"gabinetes/",
	//			"gabinetes-con-fuente/",
	//			"gabinetes/",
	//			"mouse/",
	//			"mousepads/",
	//			"teclados-kit/",
	//			"auriculares/",
	//			"parlantes/",
	//			"webcam/",
	//			"gamepad-joystick/",
	//			"impresoras/",
	//			"estabilizadores/",
	//			"sillas/",
	//			"coolers-cpu/",
	//			"water-cooling/",
	//			"cooler-fan/",
	//			"routers-y-repetidores-wifi/",
	//			"placas-de-red-usb/",
	//			"placas-de-red-internas/",
	//			"switches-de-red/",
	//			"tabletas-digitalizadoras/",
	//			"micro-sd/",
	//			"pendrive/",
	//			"adaptadores/",
	//			"cables/",
	//			"insumos/",
	//			"streaming/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-4.col-xs-6.productos.c-s",
	//			title_raw: "h2 .click",
	//			price: ".price.pull-left.precio_web",
	//			product_url: "a.click",
	//			image: ".figure img.img-responsive",
	//		},
	//		maxPages: 1, //doesn't have pages.
	//		isOutOfStock: (element) => element.textContent.includes("Sin Stock"),
	//	}),
	//
	//	goldenTech: new SiteConfig({
	//		name: "GoldenTech Store",
	//		siteImage: "/images/stores/goldentech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://goldentechstore.com.ar/",
	//		categories: [
	//			"almacenamiento/",
	//			"motherboards/",
	//			"fuentes/",
	//			"placas-de-video/",
	//			"gabinetes/",
	//			"procesadores/",
	//			"memorias-ram/",
	//			"refrigeracion/",
	//			"pc-armadas/",
	//			"monitores/",
	//			"conectividad/",
	//			"perifericos/",
	//			"sillas-gamer/",
	//			"notebooks/",
	//			"accesorios/",
	//			"outlet/",
	//		],
	//		selectors: {
	//			productWrapper: ".product.type-product",
	//			title_raw: ".woocommerce-loop-product__title a",
	//			price: ".woocommerce-Price-amount bdi",
	//			product_url: ".post_image a",
	//			image: ".attachment-woocommerce_thumbnail",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	hfTecnologia: new SiteConfig({
	//		name: "HF Tecnologia",
	//		siteImage: "/images/stores/hftecnologia.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://hftecnologia.com.ar/",
	//		categories: [
	//			"notebooks/",
	//			"pc-armadas/",
	//			"accesorios/",
	//			"componentes-de-pc/",
	//			"conectividad/",
	//			"hogar/",
	//			"impresoras/",
	//			"otros/",
	//			"perifericos/",
	//			"tabletas-graficas/",
	//			"perifericos/",
	//		],
	//		selectors: {
	//			productWrapper: ".products-list__item",
	//			title_raw: ".product-card__name h2",
	//			price: ".product-card__prices",
	//			product_url: ".product-card__name a",
	//			image: ".product-image__img",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	arShop: new SiteConfig({
	//		name: "AR Shop",
	//		siteImage: "/images/stores/arshop.png",
	//		isPcComponent: true,
	//		isSetup: true,
	//		store_url: "https://ar-shop.com.ar/",
	//		categories: [
	//			"auriculares/",
	//			"componentes-pc/",
	//			"gabinetes/",
	//			"consolas/",
	//			"monitores/",
	//			"parlantes-bt/",
	//			"perifericos/",
	//			"sillas-gamer/",
	//			"outlet/",
	//			"joystick-gamepad/",
	//			"coleccionables/",
	//			"computadoras-pc/",
	//		],
	//		selectors: {
	//			productWrapper: ".js-item-product",
	//			title_raw: ".js-item-name",
	//			price: ".js-price-display",
	//			product_url: ".item-link",
	//			image: ".js-item-image-padding img",
	//		},
	//		isOutOfStock: (element) => element.querySelector(".js-stock-label")?.style.display !== "none",
	//		maxPages: 1,
	//	}),
	//
	//	acuarioInsumos: new SiteConfig({
	//		name: "Acuario Insumos",
	//		siteImage: "/images/stores/acuarioinsumos.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.insumosacuario.com.ar/",
	//		categories: [
	//			"almacenamiento/",
	//			"audio/",
	//			"computadoras/",
	//			"conectividad/",
	//			"conectores/",
	//			"energia/",
	//			"hardware/",
	//			"monitores/",
	//			"otros/",
	//			"outlet-/",
	//			"perifericos/",
	//			"Sillas-/",
	//			"soportes/",
	//			"conectores/",
	//			"hardware/",
	//			"hardware/",
	//			"hardware/",
	//			"hardware/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".pecio_final.ft b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//	wizTech: new SiteConfig({
	//		name: "WIZ TECH",
	//		siteImage: "/images/stores/wiztech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://wiztech.com.ar/",
	//		categories: ["catalogo"],
	//		selectors: {
	//			productWrapper: ".product-selector",
	//			title_raw: ".card-title",
	//			price: ".card-description .ng-star-inserted",
	//			product_url: ".card",
	//			image: ".card-header img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//			isClientSide: true,
	//		},
	//		maxPages: 1,
	//		isOutOfStock: (element) => !element.querySelector(".card-description"),
	//	}),
	//	//xtpc has a lot of 404 issues and those thing. Wait to the future to see if it's fixed
	//	xtPc: new SiteConfig({
	//		name: "Xt-PC",
	//		siteImage: "/images/stores/xtpc.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.xt-pc.com.ar/",
	//		categories: [
	//			"cat/supra/32/notebooks/",
	//			"tag/periferico",
	//			"cat/supra/18/monitores/",
	//			"cat/supra/3/placas-de-video/",
	//			"cat/supra/1/microprocesador/",
	//			"cat/supra/12/almacenamiento/",
	//			"cat/supra/4/memorias/",
	//			"cat/supra/2/motherboard/",
	//		],
	//		selectors: {
	//			productWrapper: ".item.product-list",
	//			title_raw: ".info h3",
	//			price: ".price",
	//			product_url: "a",
	//			image: ".image img",
	//		},
	//		selectors: {
	//			productWrapper: ".item.product-list",
	//			title_raw: ".info h3",
	//			price: ".price",
	//			product_url: "a",
	//			image: ".image img",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	empenioGamer: new SiteConfig({
	//		name: "Empeño Gamer",
	//		siteImage: "/images/stores/empeniogamer.png",
	//		isPcComponent: true,
	//		isSetup: true,
	//		store_url: "https://empeniogamer.com.ar/",
	//		categories: ["tienda"],
	//		selectors: {
	//			productWrapper: ".product.type-product",
	//			title_raw: ".product-name a",
	//			price: ".woocommerce-Price-amount bdi",
	//			product_url: ".product-thumb",
	//			image: ".attachment-woocommerce_thumbnail",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".ajax_add_to_cart"),
	//		maxPages: 1,
	//	}),
	//	//
	//	hardCore: new SiteConfig({
	//		name: "HardCore",
	//		siteImage: "/images/stores/hardcore.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://hardcorecomputacion.com.ar/categoria-producto/",
	//		categories: [
	//			"microprocesadores/",
	//			"perifericos/",
	//			"sillon-gamer/",
	//			"notebooks/",
	//			"monitores/",
	//			"placas-de-red/",
	//			"conectividad/",
	//			"accesorios/",
	//			"estabilizadores-y-ups/",
	//			"outlet/",
	//			"motherboards/",
	//			"memorias/",
	//			"gabinetes/",
	//			"fuentes/",
	//			"almacenamiento/",
	//			"placasdevideo/",
	//			"cooling/",
	//		],
	//		selectors: {
	//			productWrapper: ".product.type-product",
	//			title_raw: ".woocommerce-loop-product__title",
	//			price: ".woocommerce-Price-amount bdi",
	//			product_url: ".woocommerce-LoopProduct-link",
	//			image: ".attachment-woocommerce_thumbnail",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	hyperGaming: new SiteConfig({
	//		name: "Hyper Gaming",
	//		siteImage: "/images/stores/hypergaming.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.hypergaming.com.ar/",
	//		categories: [
	//			"monitores/",
	//			"motherboards/",
	//			"notebooks/",
	//			"pc-armadas/",
	//			"perifericos/",
	//			"placas-de-video/",
	//			"procesadores/",
	//			"refrigeracion/",
	//			"seguridad/",
	//			"sillas/",
	//			"placas-de-video/",
	//			"perifericos/",
	//			"procesadores/",
	//			"notebooks/",
	//			"monitores/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".pecio_final.ft b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//			isClientSide: true,
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	ignaTech: new SiteConfig({
	//		name: "IgnaTech",
	//		siteImage: "/images/stores/ignatech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.ignatech.com.ar/",
	//		categories: [
	//			"componentes/",
	//			"conectividad/",
	//			"consolas/",
	//			"estabilizadores-y-ups/",
	//			"monitores/",
	//			"notebook/",
	//			"pc-armadas/",
	//			"perifericos/",
	//			"seguridad/",
	//			"sillas-gamer/",
	//			"televisores/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".pecio_final.ft b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//			isClientSide: true,
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	integradosArgentinos: new SiteConfig({
	//		name: "Integrados Argentinos",
	//		siteImage: "/images/stores/integradosargentinos.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.integradosargentinos.com/",
	//		categories: [
	//			"listado/computacion/pc-escritorio/pc/",
	//			"listado/computacion/accesorios-pc-gaming/auriculares/",
	//			"listado/computacion/monitores-accesorios/monitores/",
	//			"disco_DisplayType_G",
	//			"listado/consolas-videojuegos/accesorios-pc-gaming/auriculares/",
	//			"listado/computacion/laptops-accesorios/notebooks/",
	//			"listado/computacion/componentes-pc/",
	//			"listado/computacion/perifericos-pc/mouses-teclados/teclados/",
	//			"listado/computacion/perifericos-pc/mouses-teclados/mouses/",
	//			"listado/computacion/perifericos-pc/mouses-teclados/mouse-pads/",
	//			"listado/computacion/perifericos-pc/webcams/",
	//			"listado/computacion/perifericos-pc/mouses-teclados/kits-mouse-teclado/",
	//			"listado/computacion/accesorios-pc-gaming/auriculares/",
	//			"listado/computacion/accesorios-pc-gaming/microfonos/",
	//		],
	//		selectors: {
	//			productWrapper: ".ui-search-result__wrapper",
	//			title_raw: ".poly-component__title",
	//			price: ".andes-money-amount__fraction",
	//			product_url: ".poly-component__title",
	//			image: ".poly-component__picture",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".poly-price__current"),
	//		maxPages: 1,
	//	}),
	//	//
	//	katech: new SiteConfig({
	//		name: "Katech",
	//		siteImage: "/images/stores/katech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://katech.com.ar/",
	//		categories: [
	//			"hardware/",
	//			"categoria/gameroom/",
	//			"categoria/monitores/",
	//			"categoria/conectividad-y-redes/",
	//			"categoria/accesorios/",
	//			"categoria/pc-gamer/",
	//			"categoria/notebooks/notebooks-gamer/",
	//			"categoria/notebooks/notebooks-oficina/",
	//			"categoria/mouse/",
	//			"categoria/teclados/",
	//			"categoria/auriculares-y-microfonos/",
	//			"categoria/parlantes/",
	//			"categoria/camaras/",
	//			"categoria/volantes/",
	//		],
	//		selectors: {
	//			productWrapper: ".w-grid-item.product.type-product",
	//			title_raw: ".post_title a",
	//			price: ".woocommerce-Price-amount.amount bdi",
	//			product_url: ".post_title a",
	//			image: ".wp-post-image",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//		isOutOfStock: (element) => element.textContent.includes("Sin Stock"),
	//	}),
	//	//
	//	liontech: new SiteConfig({
	//		name: "Liontech Gaming",
	//		siteImage: "/images/stores/liontech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.liontech-gaming.com/",
	//		categories: [
	//			"product-category/componentes-de-pc/",
	//			"product-category/perifericos/",
	//			"product-category/conectividad/",
	//			"product-category/almacenamiento/",
	//			"product-category/combo-actualizacion/",
	//			"ofertas/",
	//			"product-category/pc-armada/",
	//			"product-category/notebooks/",
	//			"product-category/tablet/",
	//			"product-category/outlet/",
	//			"product-category/monitores/",
	//			"product-category/consolas/",
	//			"product-category/pc-armada/",
	//		],
	//		selectors: {
	//			productWrapper: ".product-inner",
	//			title_raw: ".woocommerce-loop-product__title",
	//			price: ".woocommerce-Price-amount.amount bdi",
	//			product_url: ".product-loop-title",
	//			image: ".wp-post-image",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//	}),
	//	//
	//	malditoHard: new SiteConfig({
	//		name: "Maldito Hard",
	//		siteImage: "/images/stores/malditohard.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.malditohard.com.ar/",
	//		categories: [
	//			"categoria/pc-gamer/",
	//			"categoria/pcs-armadas/",
	//			"categoria/sillas-gamer/",
	//			"categoria/monitores/",
	//			"categoria/placa-de-video/",
	//			"categoria/notebooks/",
	//			"hardware/",
	//			"categoria/accesorios/",
	//			"categoria/tecnologia/",
	//			"/hardware/?filter_product_cat=auriculares,mouses,parlantes,teclados",
	//		],
	//		selectors: {
	//			productWrapper: ".w-grid-item.product.type-product",
	//			title_raw: ".woocommerce-loop-product__title a",
	//			price: ".woocommerce-Price-amount.amount bdi",
	//			product_url: ".post_image a",
	//			image: ".wp-post-image",
	//		},
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//	}),
	//	//
	//	maxTecno: new SiteConfig({
	//		name: "Max Tecno",
	//		siteImage: "/images/stores/maxtecno.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://maxtecno.com.ar/",
	//		categories: [
	//			"equipos-armados/",
	//			"monitores/",
	//			"notebooks/",
	//			"impresoras/",
	//			"seguridad/",
	//			"ofertas/",
	//			"categoria/perifericos/teclados-perifericos/",
	//			"categoria/perifericos/parlantes-periféricos/",
	//			"categoria/perifericos/joystick-periféricos/",
	//			"categoria/perifericos/auriculares-periféricos/",
	//			"categoria/perifericos/mouse-pad-periféricos/",
	//			"categoria/perifericos/mouse-perifericos/",
	//			"categoria/perifericos/volantes-periféricos/",
	//			"categoria/sillas/sillas-gamer-sillas/",
	//			"categoria/estbilizador/estabilizador-de-tension-estbilizador/",
	//		],
	//		selectors: {
	//			productWrapper: ".w-grid-item.product.type-product",
	//			title_raw: ".woocommerce-loop-product__title a",
	//			price: ".woocommerce-Price-amount.amount bdi",
	//			product_url: ".post_image a",
	//			image: ".attachment-woocommerce_thumbnail",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".add_to_cart_button"),
	//		pagination: {
	//			type: "path",
	//			param: "page/{page}",
	//		},
	//	}),
	//	//
	//	megasoft: new SiteConfig({
	//		name: "Megasoft",
	//		siteImage: "/images/stores/megasoft.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.megasoftargentina.com.ar/",
	//		categories: [
	//			"accesorios---cables/",
	//			"Auriculares---Microfonos/",
	//			"Combo-Actualizacion/",
	//			"Conectividad_2/",
	//			"consolas/",
	//			"Coolers---Watercooling/",
	//			"Fuentes---Ups---Estabilizadores/",
	//			"Gabinetes_2/",
	//			"Impresoras---Insumos/",
	//			"Joystick/",
	//			"Memorias-Ram-/",
	//			"Mini-Pc/",
	//			"Monitores/",
	//			"Motherboards/",
	//			"Notebooks/",
	//			"Parlantes---Audio/",
	//			"Pc-Armadas_2/",
	//			"Pendrives---Micro-Sd/",
	//			"Perifericos-Pc/",
	//			"Placas-De-Sonido/",
	//			"Placas-De-Video/",
	//			"Procesadores/",
	//			"rigidos---solidos/",
	//			"sillas-y-mesa-gamer/",
	//			"soporte-tecnico/",
	//			"Soportes/",
	//			"streaming-media-player/",
	//			"super-ofertas/",
	//			"televisores/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".pecio_final.ft b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		isOutOfStock: (element) =>
	//			element.querySelector(".orange.et")?.textContent.includes("Bajo stock"),
	//		pagination: {
	//			type: "queryParam",
	//			param: "page/{page}",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	mexx: new SiteConfig({
	//		name: "Mexx",
	//		siteImage: "/images/stores/mexx.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.mexx.com.ar/productos-rubro/",
	//		categories: [
	//			"tablets/",
	//			"notebooks/",
	//			"motherboards/",
	//			"procesadores/",
	//			"memorias-ram/",
	//			"almacenamiento/",
	//			"placas-de-video/",
	//			"fuentes-de-poder/",
	//			"gabinetes/",
	//			"refrigeracion-pc/",
	//			"gabinetes/",
	//			"combos-actualizacion-pc/",
	//			"teclados,-mouses-y-pads/",
	//			"auriculares-y-microfonos-/",
	//			"camaras-web-e-ip/",
	//			"streaming-/",
	//			"monitores/",
	//			"conectividad-y-redes/",
	//			"ups-y-estabilizadores/",
	//			"sillas-y-escritorios-gamers-/",
	//			"consolas-/",
	//			"volantes-y-gamepads/",
	//			"parlantes-y-audio/",
	//			"proyectores-/",
	//			"tabletas-graficas/",
	//			"tv-/",
	//			"cables/",
	//			"outlet/",
	//		],
	//		selectors: {
	//			productWrapper: ".productos.col-md-4.pull-left",
	//			title_raw: ".card-title a",
	//			price: ".card-footer b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20 img",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".btn-success.btn-xs.enstocklistado"),
	//		pagination: {
	//			type: "queryParam",
	//			param: "pagina",
	//		},
	//	}),
	//	noxieStore: new SiteConfig({
	//		name: "Noxie Store",
	//		siteImage: "/images/stores/noxiestore.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.noxiestore.com/",
	//		categories: [
	//			"teclados-y-mouses/",
	//			"almacenamiento/",
	//			"audio/",
	//			"cables-y-adaptadores/",
	//			"combo-actualizacion/",
	//			"conectividad-y-redes/",
	//			"gabinetes/",
	//			"gamepad---joystick/",
	//			"memorias-ram/",
	//			"monitores-y-televisores/",
	//			"mother/",
	//			"pc-armadas/",
	//			"placas-de-video/",
	//			"procesadores/",
	//			"refrigeracion/",
	//			"sillas-gamers/",
	//		],
	//		selectors: {
	//			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
	//			title_raw: ".card-title a",
	//			price: ".pecio_final.ft b",
	//			product_url: ".card-title a",
	//			image: ".view.overlay.px-20.imagen img",
	//		},
	//		pagination: {
	//			type: "queryParam",
	//			param: "page",
	//		},
	//		isOutOfStock: (element) => !element.querySelector(".btn-blue-link.et"),
	//	}),
	//	//
	//	peakComputacion: new SiteConfig({
	//		name: "Peak Computacion",
	//		siteImage: "/images/stores/peakcomputacion.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.peakcomputacion.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	rocketHard: new SiteConfig({
	//		name: "Rocket Hard",
	//		siteImage: "/images/stores/rockethard.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.rockethard.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	scpHardstore: new SiteConfig({
	//		name: "SCP Hardstore",
	//		siteImage: "/images/stores/scphardstore.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.scphardstore.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	shopGamer: new SiteConfig({
	//		name: "ShopGamer",
	//		siteImage: "/images/stores/shopgamer.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.shopgamer.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	space: new SiteConfig({
	//		name: "Space",
	//		siteImage: "/images/stores/space.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.space.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	theGamerShop: new SiteConfig({
	//		name: "The Gamer Shop",
	//		siteImage: "/images/stores/thegamershop.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.thegamershop.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	tiendaTrade: new SiteConfig({
	//		name: "Tiendatrade",
	//		siteImage: "/images/stores/tiendatrade.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.tiendatrade.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	turtech: new SiteConfig({
	//		name: "Turtech",
	//		siteImage: "/images/stores/turtech.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.turtech.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	//
	//	uranoStream: new SiteConfig({
	//		name: "Urano Stream",
	//		siteImage: "/images/stores/uranostream.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.uranostream.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//	gorilaGames: new SiteConfig({
	//		name: "Urano Stream",
	//		siteImage: "/images/stores/uranostream.png",
	//		isPcComponent: true,
	//		isSetup: false,
	//		store_url: "https://www.uranostream.com.ar",
	//		categories: ["/productos"],
	//		selectors: {
	//			productWrapper: "",
	//			title_raw: "",
	//			price: "",
	//			product_url: "",
	//			image: "",
	//		},
	//		maxPages: 1,
	//	}),
	//
	//
};