import { SiteConfig } from "./siteConfig.mjs";

export const siteConfigs = {
	armyTech: new SiteConfig({
		store_name: "ArmyTech",
		store_id: "armytech",
		store_url: "https://www.armytech.com.ar",
		store_image: "/src/assets/stores/armytech.png",
		trust_factor_manual: 90,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "buenos aires", "buena_reputacion", "componentes"],
		pages: [
			"/371-pc-hogar-oficina",
			"/370-pc-gamer",
			"/494-pc-diseno",
			"/372-mini-pc",
			"/508-notebook-oficina",
			"/507-notebook-gamer",
			"/506-notebook-diseno",
			"/510-mochilas",
			"/478-sistemas-operativos",
			"/414-motherboards",
			"/499-kit-teclado-y-mouse",
			"/440-mouse",
			"/444-teclados",
			"/441-mousepad",
			"/437-auriculares",
			"/439-joystick",
			"/442-parlantes",
			"/364-webcam",
			"/495-silla-gamer",
			"/433-monitores-oficina",
			"/432-monitores-gamer",
			"/435-tvs",
			"/423-impresoras-laser",
			"/424-impresoras-inkjet",
			"/425-impresoras-multifuncion",
			"/502-toners",
			"/376-placas-de-red",
			"/377-placas-wifi",
			"/500-cables-av",
			"/379-router-wifi",
			"/380-switch",
			"/374-access-point",
			"/390-estabilizadores",
			"/393-ups",
			"/365-computadoras",
			"/418-placas-de-video",
			"/419-procesadores",
			"/412-memorias",
			"/content/30-royal-kludge",
			"/2-productos",
			"/359-accesorios",
			"/366-aio",
			"/367-combos-de-actualizacion",
			"/368-gamerbox",
			"/369-pc-armada",
			"/373-conectividad",
			"/375-cable-red",
			"/378-router",
			"/389-energia",
			"/391-pdu",
			"/392-powerbanks",
			"/398-gaming-house",
			"/399-gamepad",
			"/400-juegos",
			"/401-perifericos2",
			"/402-play-station",
			"/403-volantes",
			"/404-xbox",
			"/496-streaming",
			"/497-televisores",
			"/498-microfono",
			"/509-escritorios",
			"/405-hardware",
			"/406-combos-de-actualizacion",
			"/407-fuentes",
			"/408-gabinetes-con-psu",
			"/409-gabinetes-sin-psu",
			"/410-hdd",
			"/411-hde",
			"/413-memorias-soddimm",
			"/415-lectograbadoras",
			"/416-perifericos3",
			"/417-placas-de-sonido",
			"/420-refrigeracion",
			"/421-ssd",
			"/422-impresoras",
			"/501-impresoras-de-sistema-continuo",
			"/431-monitores-y-tvs",
			"/434-monitores-profesionales",
			"/436-perifericos",
			"/438-gamepads",
			"/443-sillas-gamer",
			"/518-adaptadores",
			"/445-portables",
			"/446-2en1",
			"/447-celulares",
			"/448-gamerbook",
			"/449-notebooks",
			"/451-wearables",
			"/475-software",
			"/476-antivirus",
			"/477-licencias",
			"/479-videovigilancia",
			"/493-selecciona-tu-marca",
			"/480-sonido-video",
			"/481-auriculares",
			"/482-capturadoras",
			"/483-parlantes",
			"/484-portatiles",
			"/485-proyectores",
			"/486-streaming",
			"/487-videovigilancia",
			"/488-accesorios",
			"/489-camaras-analogicas",
			"/490-camaras-ip",
			"/491-dvr",
			"/492-nvr",
			"/511-camaras-wifi-interior",
			"/512-camaras-wifi-exterior",
			"/503-accesorios",
			"/360-adaptadores",
			"/361-cable-datos",
			"/362-cable-power",
			"/363-soportes-led",
			"/504-administracion",
			"/505-notebooks",
			"/514-tablets",
			"/515-consumo",
			"/516-digitalizadora-grafica",
			"/517-smart-home",
			"/519-outlet",
			"/520-simuladores",
			"/521-simulador-de-auto",
			"/522-simulador-de-vuelo",
			"/523-soporte-para-monitores",
			"/content/15-arma-tu-pc",
			"/brand/16-gigabyte",
			"/brand/212-jiushark",
			"/content/23-corsair",
			"/module/iqitsearch/searchiqit",
			"/470-refrigeracion",
			"/blog/articulos/mac-os-vs-windows-vs-linux",
			"/blog/articulos",
			"/brand/17-msi",
			"/brand/26-amd",
			"/brand/27-corsair",
			"/brand/49-coolermaster",
			"/brand/170-xpg",
			"/brand/80-adata",
			"/brand/152-aerocool",
			"/brand/25-intel",
			"/brand/23-kingston",
			"/brand/81-logitech",
			"/content/16-quienes-somos",
			"/content/3-terminos-y-condiciones-de-uso",
			"/content/17-boton-de-arrepentimiento",
			"/367-combos",
			"/4629-powerbank",
			"/420-reffrigeracion",
			"//fonts.googleapis.com/css",
			"/418-placa-de-video",
			"/436-Perifericos-army",
			"/416-perifericos",
		],
		selectors: {
			productWrapper: ".js-product-miniature-wrapper",
			title_raw: ".h3.product-title a",
			price: ".product-price",
			product_url: ".h3.product-title a",
			image_url: ".product-thumbnail img",
			stock_raw: null, // no tiene info de stock, pero todos los productos que muestran están en stock
			installmentes: null, // no tienen info de cuotas por ahora
		},
		timeout: 30000,
	}),
	//
	venex: new SiteConfig({
		store_name: "Venex",
		store_id: "venex",
		store_url: "https://www.venex.com.ar",
		store_image: "/images/stores/venex.png",
		trust_factor_manual: 85,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "cordoba", "buena_reputacion", "componentes"],
		pages: [
			"/componentes-de-pc/discos-duros-mecanicos",
			"/componentes-de-pc/discos-solidos-ssd",
			"/componentes-de-pc/memorias-ram/desktop",
			"/componentes-de-pc/memorias-ram/notebook",
			"/componentes-de-pc/microprocesadores",
			"/componentes-de-pc/motherboards/amd",
			"/componentes-de-pc/motherboards/intel",
			"/componentes-de-pc/placas-de-video",
			"/componentes-de-pc/gabinetes",
			"/componentes-de-pc/placas-de-sonido",
			"/componentes-de-pc/fuentes",
			"/componentes-de-pc/pastas-termicas",
			"/componentes-de-pc/placas-de-red",
			"/componentes-de-pc/refrigeracion/fan-coolers",
			"/componentes-de-pc/combos-de-actualizaciones",
			"/pc-de-escritorio/pcs-de-escritorio",
			"/pc-de-escritorio/mini-pcs",
			"/pc-de-escritorio/combos-de-actualizacion",
			"/pc-de-escritorio/powered-by-asus",
			"/notebooks",
			"/monitores/19-a-26-pulgadas",
			"/monitores/27-a-32-pulgadas",
			"/monitores/33-pulgadas-y-superior",
			"/monitores/proyectores-y-pantallas",
			"/perifericos/teclados",
			"/perifericos/gaming-kit",
			"/perifericos/teclados---mouse",
			"/perifericos/mousepads",
			"/perifericos/mouse",
			"/perifericos/auriculares/gamer",
			"/perifericos/auriculares/oficina-y-urbano",
			"/perifericos/parlantes/para-pc",
			"/perifericos/parlantes/portatiles",
			"/perifericos/joystick-y-volantes",
			"/perifericos/webcams",
			"/perifericos/punteros-laser-y-presentadores",
			"/perifericos/lectores-codigo-de-barras",
			"/perifericos/microfonos",
			"/conectividad-y-redes/access-point",
			"/conectividad-y-redes/modem-router",
			"/conectividad-y-redes/routers",
			"/conectividad-y-redes/switchs",
			"/impresion-y-scanners/impresoras-laser",
			"/impresion-y-scanners/impresoras-sistema-continuo",
			"/impresion-y-scanners/impresoras-termicas",
			"/impresion-y-scanners/impresion-3d/impresoras-3d",
			"/impresion-y-scanners/impresion-3d/consumibles",
			"/impresion-y-scanners/toners",
			"/impresion-y-scanners/cartuchos-de-tinta",
			"/relojes-smartwatch",
			"/almacenamiento-portatil/microsd",
			"/almacenamiento-portatil/pendrives",
			"/almacenamiento-portatil/discos-externos",
			"/tablets",
			"/tabletas-digitalizadoras",
			"/televisores-y-tv-box/smart-tvs",
			"/televisores-y-tv-box/tv-box",
			"/streaming",
			"/software",
			"/camaras-ip",
			"/accesorios/fundas-y-mochilas",
			"/accesorios/bases-rrefrigerantes",
			"/accesorios/cargadores",
			"/accesorios/cables",
			"/accesorios/merchandising",
			"/soportes",
			"/sillas-gamers/sillas-gamer",
			"/estabilizadores-ups-y-zapatillas/estabilizadores",
			"/estabilizadores-ups-y-zapatillas/ups",
			"/estabilizadores-ups-y-zapatillas/zapatillas",
			"/componentes-de-pc",
			"/componentes-de-pccomponentes-de-pc/memorias-ram",
			"/componentes-de-pccomponentes-de-pc/motherboards",
			"/componentes-de-pccomponentes-de-pc/gabinetes",
			"/componentes-de-pccomponentes-de-pc/fuentes",
			"/componentes-de-pccomponentes-de-pc/placas-de-red",
			"/componentes-de-pccomponentes-de-pc/refrigeracion",
			"/pc-de-escritorio",
			"/pc-de-escritoriopc-de-escritorio/mini-pcs",
			"/pc-de-escritoriopc-de-escritorio/powered-by-asus",
			"/monitores",
			"/monitoresmonitores/19-a-26-pulgadas",
			"/monitoresmonitores/27-a-32-pulgadas",
			"/monitoresmonitores/33-pulgadas-y-superior",
			"/monitoresmonitores/proyectores-y-pantallas",
			"/perifericos",
			"/perifericosperifericos/teclados",
			"/perifericosperifericos/gaming-kit",
			"/perifericosperifericos/teclados---mouse",
			"/perifericosperifericos/mousepads",
			"/perifericosperifericos/mouse",
			"/perifericosperifericos/auriculares",
			"/perifericosperifericos/auriculares/gamer",
			"/perifericosperifericos/parlantes",
			"/perifericosperifericos/parlantes/para-pc",
			"/perifericosperifericos/parlantes/portatiles",
			"/perifericosperifericos/joystick-y-volantes",
			"/perifericosperifericos/webcams",
			"/perifericosperifericos/lectores-codigo-de-barras",
			"/perifericosperifericos/microfonos",
			"/conectividad-y-redes",
			"/conectividad-y-redesconectividad-y-redes/routers",
			"/conectividad-y-redesconectividad-y-redes/switchs",
			"/impresion-y-scanners",
			"/impresion-y-scannersimpresion-y-scanners/toners",
			"/almacenamiento-portatil",
			"/televisores-y-tv-box",
			"/televisores-y-tv-boxtelevisores-y-tv-box/tv-box",
			"/accesorios",
			"/accesoriosaccesorios/fundas-y-mochilas",
			"/accesoriosaccesorios/bases-rrefrigerantes",
			"/accesoriosaccesorios/cargadores",
			"/accesoriosaccesorios/cables",
			"/accesoriosaccesorios/merchandising",
			"/sillas-gamers",
			"/sillas-gamerssillas-gamers/sillas-gamer",
			"/estabilizadores-ups-y-zapatillas",
			"/corporativo.htm",
			"/nvidia.htm",
			"/kingstonfury-vx.htm",
			"/amd-micrositio.htm",
			"/msi.htm",
			"/redragon-venex.htm",
			"/hyperx-micro.htm",
			"/micrositio-palit.htm",
			"/logitech-vx.htm",
			"/xpg-vx.htm",
			"/kingston-vx.htm",
			"/thermaltake-vx.htm",
			"/ADATA-VX.htm",
			"/gamdias-vx.htm",
			"/xiaomi-vx.htm",
			"/resultado-busqueda.htm",
			"/Venex-Days-Notebooks.htm",
			"/computadoras-y-servidores/pcs-de-escritorio",
			"/v-days-gamer.htm",
			"/apple.htm",
			"/hyperxmicro.htm",
			"/aorus.htm",
			"/kingston.htm",
			"/precios-explosivos.htm",
		],
		selectors: {
			productWrapper: ".js-product-miniature-wrapper",
			title_raw: ".h3.product-title a",
			price: ".product-price",
			product_url: ".h3.product-title a",
			image_url: ".product-thumbnail img",
			stock_raw: null, // no tiene info de stock, pero todos los productos que muestran están en stock
			installmentes: null, // no tienen info de cuotas por ahora
		},
		timeout: 30000,
	}),
	//
	maximus: new SiteConfig({
		store_name: "Maximus",
		store_id: "maximus",
		store_url: "https://www.maximus.com.ar",
		store_image: "/images/stores/maximus.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/Productos/maximus.aspx",
			"/armarpc/armar-pc/maximus.aspx",
			"/combopc/combo-pc/maximus.aspx",
			"/rma/garantia/maximus.aspx",
			"/Productos/Computadoras/maximus.aspx",
			"/Productos/Computadoras/Baja/maximus.aspx",
			"/Productos/Computadoras/Media/maximus.aspx",
			"/Productos/Computadoras/Alta/maximus.aspx",
			"/Productos/Notebooks/maximus.aspx",
			"/Productos/Notebooks/Notebooks-AMD/maximus.aspx",
			"/Productos/Notebooks/Notebooks-Intel/maximus.aspx",
			"/Productos/Accesorios/maximus.aspx",
			"/Productos/Perifericos/Mouse/maximus.aspx",
			"/Productos/Perifericos/Mouse-Pad/maximus.aspx",
			"/Productos/Combo-Actualizaci%C3%B3n-/maximus.aspx",
			"/Productos/Microprocesadores/maximus.aspx",
			"/Productos/Motherboards/maximus.aspx",
			"/Productos/Motherboards/AMD-AM4/maximus.aspx",
			"/Productos/Motherboards/AMD-AM5/maximus.aspx",
			"/Productos/Motherboards/Intel-1700/maximus.aspx",
			"/Productos/Motherboards/Intel-1200/maximus.aspx",
			"/Productos/Motherboards/Intel-1851/maximus.aspx",
			"/Productos/Placas-De-Video/maximus.aspx",
			"/Productos/Memorias/maximus.aspx",
			"/Productos/Almacenamiento/maximus.aspx",
			"/Productos/Refrigeracion-Pc/maximus.aspx",
			"/Productos/Refrigeracion-Pc/Cooler/maximus.aspx",
			"/Productos/Gabinetes/maximus.aspx",
			"/Productos/Gabinetes/Mini-Tower/maximus.aspx",
			"/Productos/Gabinetes/Mid-Tower/maximus.aspx",
			"/Productos/Gabinetes/Full-Tower/maximus.aspx",
			"/Productos/Fuentes/maximus.aspx",
			"/Productos/Perifericos/maximus.aspx",
			"/Productos/Perifericos/Teclados/maximus.aspx",
			"/Productos/Perifericos/Auriculares/maximus.aspx",
			"/Productos/Perifericos/Volantes/maximus.aspx",
			"/Productos/Perifericos/Parlantes/maximus.aspx",
			"/Productos/Perifericos/Microfonos/maximus.aspx",
			"/Productos/Perifericos/Joystick/maximus.aspx",
			"/Productos/Perifericos/Webcam/maximus.aspx",
			"/Productos/Perifericos/Accesorios/maximus.aspx",
			"/Productos/Monitores/maximus.aspx",
			"/Productos/Sillas/maximus.aspx",
			"/Productos/Escritorios/maximus.aspx",
			"/Productos/Conectividad/maximus.aspx",
			"/Productos/Conectividad/Routers/maximus.aspx",
			"/Productos/Accesorios/Cables-Mod/maximus.aspx",
			"/Productos/Accesorios/DRIVE-BAY/maximus.aspx",
			"/Productos/Accesorios/Soportes/maximus.aspx",
			"/Productos/Accesorios/Key-caps/maximus.aspx",
			"/Productos/Accesorios/Herramientas/maximus.aspx",
			"/Productos/Impresoras/maximus.aspx",
			"/Productos/Capturadoras-De-Video/maximus.aspx",
			"/Productos/OUTLET/maximus.aspx",
			"/MICUENTA/P=0/maximus.aspx",
			"/LOGIN/login/maximus.aspx",
			"/Productos/microprocesadores/maximus.aspx",
			"/Productos/gabinetes/maximus.aspx",
			"/Productos/combo-actualizacion/maximus.aspx",
			"/Productos/outlet/outlets/maximus.aspx",
			"/Productos/computadoras/maximus.aspx",
			"/Productos/Genesis/maximus.aspx",
			"/Productos/Intel/maximus.aspx",
			"/Productos/AMD/maximus.aspx",
			"/Productos/Asus/maximus.aspx",
			"/Productos/Nvidia/maximus.aspx",
			"/Productos/Kingston/maximus.aspx",
			"/Productos/Gigabyte/maximus.aspx",
			"/Productos/Razer/maximus.aspx",
			"/Productos/MSI/maximus.aspx",
			"/Productos/CORSAIR/maximus.aspx",
			"/Productos/placas-de-video/maximus.aspx",
			"/productos/Monitores/Monitores-144Hz/maximus.aspx",
			"/Productos/Monitores/Monitores-240Hz/maximus.aspx",
			"/Productos/refrigeracion/maximus.aspx",
			"/Productos/fuentes/maximus.aspx",
		],
		selectors: {
			productWrapper: ".col-md-prod",
			title_raw: ".title-prod",
			image: ".image img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	compraGamer: new SiteConfig({
		store_name: "CompraGamer",
		store_id: "compragamer",
		store_url: "https://compragamer.com/productos?",
		store_image: "/images/stores/compragamer.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes", "precio", "mayorista"],
		pages: [
			"cate=58",
			"cate=59",
			"cate=27",
			"cate=48",
			"cate=26",
			"cate=49",
			"cate=62",
			"cate=15",
			"cate=47",
			"cate=16",
			"cate=19",
			"cate=81",
			"cate=90",
			"cate=35",
			"cate=36",
			"cate=67",
			"cate=7",
			"cate=100",
			"cate=34",
			"cate=5",
			"cate=8",
			"cate=39",
			"cate=2",
			"cate=13",
			"cate=18",
			"cate=38",
			"cate=65",
			"cate=72",
			"cate=74",
			"cate=84",
			"cate=113",
			"cate=66",
			"cate=14",
			"cate=83",
			"cate=31",
			"cate=111",
			"cate=21",
			"cate=3",
			"cate=24",
		],
		selectors: {
			productWrapper: "cgw-product-card",
			title_raw: "h3.product-card__title",
			price: ".product-card__cart__price--current",
			product_url: "a",
			image_url: ".medium product-card__image img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	ngTech: new SiteConfig({
		store_name: "NGTech",
		store_id: "ngtech",
		store_url: "https://www.ngtechnologies.com.ar",
		store_image: "/images/stores/ngtech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/search/?q=*"],
		selectors: {
			productWrapper: ".js-product-container",
			title_raw: ".js-item-name",
			price: ".js-price-display",
			product_url: "a",
			image_url: "img.js-product-item-image-private",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	mgmGamers: new SiteConfig({
		store_name: "MGM Gamers",
		store_id: "mgmgamers",
		store_url: "https://mgmgamers.store",
		store_image: "/images/stores/mgmgamers.png",
		trust_factor_manual: 70,
		seller_type: ["setup"],
		tags: ["gaming", "argentina", "setup"],
		pages: ["/search/?q=*"],
		selectors: {
			productWrapper: ".js-item-product",
			title_raw: ".js-item-name",
			price: "[data-product-price]",
			product_url: ".item-link",
			image_url: ".js-item-image-padding img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	slotOne: new SiteConfig({
		store_name: "Slot-One",
		store_id: "slotone",
		store_url: "https://www.slot-one.com.ar",
		store_image: "/images/stores/slotone.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/search/?q=*"],
		selectors: {
			productWrapper: ".js-product-container",
			title_raw: ".js-item-name",
			price: ".js-price-display",
			product_url: "a",
			image_url: "img.js-product-item-image-private",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	puertoMinero: new SiteConfig({
		store_name: "Puerto Minero",
		store_id: "puertominero",
		store_url: "https://www.puertominero.com.ar",
		store_image: "/images/stores/puertominero.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: ".product-card-one",
			title_raw: ".title",
			price: ".price",
			product_url: "a",
			image_url: "img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	tech710: new SiteConfig({
		store_name: "710Tech",
		store_id: "710tech",
		store_url: "https://www.710tech.com.ar/",
		store_image: "/images/stores/710tech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"accesorios/",
			"almacenamiento/",
			"combos/",
			"consolas/",
			"equipos/",
			"fuente/",
			"gabinetes/",
			"memoria-ram/",
			"monitores/",
			"motherboard/",
			"notebook/",
			"parlantes/",
			"perifericos-/",
			"placas-de-video/",
			"procesadores/",
			"refrigeracion-/",
		],
		selectors: {
			productWrapper: "div.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".price, .card-description",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	bytes37: new SiteConfig({
		store_name: "37 Bytes",
		store_id: "bytes37",
		store_url: "https://www.37bytes.com.ar/",
		store_image: "/images/stores/37bytes.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["productos/"],
		selectors: {
			productWrapper: ".js-product-container",
			title_raw: ".js-item-name",
			price: ".js-price-display",
			product_url: "a",
			image_url: "img.js-product-item-image-private",
		},
		timeout: 30000,
	}),
	//
	dinobyte: new SiteConfig({
		store_name: "Dinobyte",
		store_id: "dinobyte",
		store_url: "https://dinobyte.ar/categoria-producto/",
		store_image: "/images/stores/dinobyte.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/categoria-producto/hardware/",
			"/categoria-producto/hardware/microprocesadores/",
			"/categoria-producto/hardware/discos/",
			"/categoria-producto/hardware/discos/memorias-sd/",
			"/categoria-producto/hardware/discos/pendrives/",
			"/categoria-producto/hardware/placas-de-video/",
			"/categoria-producto/hardware/refrigeracion/",
			"/categoria-producto/equipos/",
			"/categoria-producto/equipos/pc-amd/",
			"/categoria-producto/equipos/pc-intel/",
			"/categoria-producto/equipos/notebooks/",
			"/categoria-producto/monitores/",
			"/categoria-producto/monitores/monitores-gamer/",
			"/categoria-producto/perifericos/",
			"/categoria-producto/perifericos/mouses/",
			"/categoria-producto/perifericos/mouse-pads/",
			"/categoria-producto/perifericos/teclados/",
			"/categoria-producto/perifericos/auriculares/",
			"/categoria-producto/perifericos/microfonos/",
			"/categoria-producto/perifericos/parlantes/",
			"/categoria-producto/perifericos/webcams/",
			"/categoria-producto/perifericos/joysticks/",
			"/categoria-producto/otros/",
			"/categoria-producto/otros/sillas/",
			"/categoria-producto/otros/red-wifi-bluetooth/",
			"/categoria-producto/otros/ups-de-respaldo/",
			"/categoria-producto/otros/celulares/",
			"/categoria-producto/otros/impresoras/",
			"/categoria-producto/otros/scanner/",
			"/categoria-producto/otros/proyectores/",
			"/categoria-producto/otros/capturadoras/",
			"/categoria-producto/otros/camaras-de-vigilancia/",
			"/categoria-producto/otros/televisores/",
			"/categoria-producto/otros/tabletas/",
			"/categoria-producto/apple/",
			"/categoria-producto/apple/productos-apple/",
			"/categoria-producto/apple/accesorios-apple/",
			"/categoria-producto/go-pro/",
			"/categoria-producto/go-pro/productos-go-pro/",
			"/categoria-producto/go-pro/accesorios-go-pro/",
			"/categoria-producto/consolas/",
			"/categoria-producto/hardware/gabinetes/",
			"/categoria-producto/gabinetes/",
			"/categoria-producto/hardware/memorias-ram/",
			"/categoria-producto/memorias-ram/",
			"/categoria-producto/microprocesadores/",
			"/categoria-producto/mouses/",
			"/categoria-producto/notebooks/",
			"/categoria-producto/placas-de-video/",
			"/categoria-producto/hardware/placas-madre/",
			"/categoria-producto/placas-madre/",
			"/categoria-producto/refrigeracion/",
			"/categoria-producto/sillas/",
			"/producto/motherboard-asus-prime-b860m-k-d5/",
			"/producto/motherboard-asus-prime-b760m-k-d5/",
			"/producto/motherboard-am5-asus-prime-b850m-a-d5/",
			"/producto/motherboard-am5-asus-b650m-ayw-wifi-d5/",
			"/producto/motherboard-am5-asus-prime-b650m-f-d5/",
			"/categoria-producto/pc-armadas/pc-intel/",
			"/producto/vga-asus-dual-rtx-3050-6g-d6/",
		],
		selectors: {
			productWrapper: ".w-grid-item-h",
			title_raw: ".post_title",
			price: ".woocommerce-Price-amount",
			product_url: ".post_image a",
			image_url: ".wp-post-image",
		},
		timeout: 30000,
	}),
	//
	fullH4rd: new SiteConfig({
		store_name: "Full H4rd",
		store_id: "fullh4rd",
		store_url: "https://fullh4rd.com.ar/",
		store_image: "/images/stores/fullh4rd.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/tag/hardware",
			"/tag/kingston",
			"/tag/watercooler_thermaltake",
			"/msi/",
			"/tag/razer_silla%20gamer",
			"/amd",
			"/cat/search/JBL%20QUANTUM",
			"/aorus-gigabyte/",
			"/cat",
			"/tag/lg",
			"/cart",
			"/ayuda",
			"/armatupc",
			"/tag/perifericos",
			"/cat/search/MONITOR",
			"/hyperx",
			"/nvidia/",
			"/astro",
			"/logitech",
			"/intel",
			"/corsair",
			"/tag/placa%20de%20video_rtx",
			"/asus",
			"/msi",
			"/cdn-cgi/l/email-protection",
			"/pcarmada/gamer",
			"/pcarmada/home",
			"/pcarmada/work",
			"/tag/placa%20de%20video",
			"/cat/115/radeon/1",
			"/cat/124/nvidia/1",
			"/cat/supra/1/microprocesador/1",
			"/tag/procesador_ryzen",
			"/tag/procesador_intel",
			"/cat/supra/2/motherboard/1",
			"/cat/supra/26/fuentes/1",
			"/cat/supra/23/refrigeracion/1",
			"/cat/supra/6/gabinetes/1",
			"/cat/supra/27/conectividad-y-redes/1",
			"/cat/supra/12/almacenamiento/1",
			"/cat/19/discos-sata/1",
			"/cat/132/discos-externos/1",
			"/cat/185/discos-ssd/1",
			"/cat/supra/4/memorias/1",
			"/tag/memoria%20ram_ddr3",
			"/tag/memoria%20ram_ddr4",
			"/tag/memoria%20ram_ddr5",
			"/tag/ddr4_sodimm",
			"/tag/ddr5_sodimm",
			"/cat/supra/8/teclados/1",
			"/cat/141/teclados-inalambricos/1",
			"/cat/140/teclados-gamer/1",
			"/cat/24/teclado-usb/1",
			"/cat/supra/14/mouses/1",
			"/cat/73/mouse-inalambrico/1",
			"/cat/45/mouse-gamer/1",
			"/cat/13/teclado-y-mouse/1",
			"/tag/auriculares",
			"/cat/search/auricular%20gamer",
			"/cat/236/auriculares-bluetooth/1",
			"/cat/96/auriculares-con-microfono/1",
			"/tag/accesorios",
			"/cat/239/mouse-pad/1",
			"/cat/154/joysticks/1",
			"/tag/streaming",
			"/cat/41/webcam/1",
			"/cat/303/microfonos/1",
			"/cat/34/capturadoras-y-sintoniz-de-tv/1",
			"/cat/search/stream%20deck",
			"/cat/search/tira%20de%20luz",
			"/cat/supra/33/pen-drives/1",
			"/cat/230/sillas-gamer/1",
			"/cat/supra/20/impresoras/1",
			"/cat/112/proyectores/1",
			"/tag/periferico",
			"/cat/supra/32/notebooks/1",
			"/cat/supra/3/placas-de-video/1",
			"/cat/supra/48/consolas/1",
			"/cat/320/bicicletas-electricas/1",
			"/cat/supra/40/tablet-y-ebook/1",
			"/cat/108/celulares/1",
			"/cat/supra/59/servidores/1",
			"/cat/supra/25/estabilizadores-y-ups/1",
			"/cat/supra/64/smart-home/1",
			"/cat/supra/60/smartwatches/1",
			"/cat/supra/18/monitores/1",
			"/cat/supra/28/auriculares-y-microfonos/1",
			"/cat/140/teclados-gamer",
			"/cat/96/auriculares-con-microfono",
			"/prod//",
			"/prod/29541/mother-msi-pro-h510m-b-ii-ddr4-s1200",
			"/prod/4521/hd-hdd-externo-1tb-wd-elements-usb-30",
			"/prod/12547/hd-ssd-1tb-wd-green-sata-iii-25",
			"/prod/16556/monitor-19-lg-led-19m38a-b",
			"/prod/18403/monitor-22-lg-led-full-hd-22mk600m-b",
		],
		selectors: {
			productWrapper: ".item.product-list",
			title_raw: ".info h3",
			price: ".price",
			product_url: "a",
			image_url: ".image img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	gnPoint: new SiteConfig({
		store_name: "GN Point",
		store_id: "gnpoint",
		store_url: "https://gnpoint.com.ar/productos/",
		store_image: "/images/stores/gnpoint.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["notebooks/", "productos/", "perifericos-de-pc/", "pc-de-escritorio/"],
		selectors: {
			productWrapper: ".product.type-product",
			title_raw: ".woocommerce-loop-product__title_ink",
			price: ".woocommerce-Price-amount bdi",
			product_url: ".woocommerce-loop-image-link",
			image_url: ".attachment-woocommerce_thumbnail.size-woocommerce_thumbnail",
		},
		timeout: 30000,
	}),
	//
	gamersPoint: new SiteConfig({
		store_name: "Gamers Point",
		store_id: "gamerspoint",
		store_url: "https://www.gamerspoint.com.ar/categoria/",
		store_image: "/images/stores/gamerspoint.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/categoria/componentes-de-pc/",
			"/categoria/componentes-de-pc/microprocesadores/",
			"/categoria/componentes-de-pc/refrigeracion/",
			"/categoria/componentes-de-pc/motherboard/",
			"/categoria/componentes-de-pc/memorias-ram/",
			"/categoria/componentes-de-pc/placas-de-video/",
			"/categoria/componentes-de-pc/disco-hdd/",
			"/categoria/componentes-de-pc/disco-ssd-m2-nvme/",
			"/categoria/componentes-de-pc/disco-ssd-m2-sata/",
			"/categoria/componentes-de-pc/disco-ssd-sata/",
			"/categoria/componentes-de-pc/fuentes/",
			"/categoria/componentes-de-pc/gabinetes/",
			"/categoria/conectividad/",
			"/categoria/perifericos/",
			"/categoria/audio/",
			"/categoria/audio/auriculares-audio/",
			"/categoria/audio/micr%c3%b3fonos/",
			"/categoria/audio/parlantes-audio/",
			"/categoria/perifericos/teclado-mouse-perifericos/",
			"/categoria/perifericos/mouse-perifericos/",
			"/categoria/perifericos/teclados-perifericos/",
			"/categoria/perifericos/webcam-perifericos/",
			"/categoria/perifericos/mousepad-perifericos/",
			"/categoria/impresoras/impresora/",
			"/categoria/almacenamiento/",
			"/categoria/tabletas-graficas/",
			"/categoria/armados-pc/",
			"/categoria/armados-pc/pc-estudio-armados-pc/",
			"/categoria/armados-pc/armados-pc-armado-pc/",
			"/categoria/armados-pc/pc-trabajo-armados-pc/",
			"/categoria/monitores/",
			"/sillas/",
			"/categoria/notebooks/",
			"/categoria/reparadores/",
			"/carrito/",
			"/corsair/",
			"/producto/notebook-hp-250g10-i3-1315u-15-8gb-256/",
			"/producto/notebook-lenovo-v15-i7-8gb-512ssd-fdos/",
			"/producto/procesador-amd-am5-ryzen-9-7950x/",
			"/producto/procesador-amd-am5-ryzen-9-9900x3d/",
			"/producto/procesador-amd-am4-ryzen-3-3200g/",
			"/producto/procesador-amd-am4-ryzen-5-5500-3-6ghz/",
			"/producto/procesador-amd-am4-ryzen-7-5700g/",
			"/producto/procesador-amd-am5-ryzen-5-9600/",
			"/producto/procesador-amd-am5-ryzen-7-8700f/",
		],
		selectors: {
			productWrapper: ".product.type-product",
			title_raw: ".woocommerce-loop-product__title",
			price: ".woocommerce-Price-amount bdi",
			product_url: ".post_image a",
			image_url: ".wp-post-image",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	GamingCity: new SiteConfig({
		store_name: "Gaming City",
		store_id: "gamingcity",
		store_url: "https://www.gamingcity.com.ar/",
		store_image: "/images/stores/gamingcity.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/p/arma-tu-pc-landing",
			"/monitores",
			"/placa-de-video",
			"/procesadores",
			"/notebooks",
			"/_DisplayType_G_BRAND_16360",
			"/listado/computacion/",
			"/listado/consolas-videojuegos/",
			"/_BRAND_15788",
			"/_BRAND_7885",
			"/_BRAND_16360",
			"/_BRAND_47354",
			"/_BRAND_7294334",
			"/_BRAND_13180685",
			"/_BRAND_41874",
			"/_BRAND_448156",
			"/_BRAND_899182",
			"/_BRAND_2796190",
			"/_BRAND_195091",
			"/_BRAND_18685",
			"/_BRAND_15795",
			"/_BRAND_9597",
			"/_BRAND_9565",
			"/_BRAND_479",
			"/_BRAND_47687",
			"/_BRAND_2542655",
			"/_BRAND_2542653",
			"/_BRAND_17992",
			"/_BRAND_17265",
			"/_BRAND_6504514",
			"/_BRAND_2017",
			"/_BRAND_16244",
			"/_BRAND_1258105",
			"/_BRAND_9593",
			"/_BRAND_9079566",
			"/_BRAND_42328",
			"/_BRAND_41057",
			"/_BRAND_4060193",
			"/_BRAND_2301927",
			"/_BRAND_17337102",
			"/_BRAND_16739",
			"/_BRAND_15162008",
			"/_BRAND_995",
			"/_BRAND_9807",
			"/_BRAND_9344",
			"/_BRAND_8784",
			"/_BRAND_80801",
			"/_BRAND_5986",
			"/p/privacidad",
			"/p/contacto",
			"/gz/cart",
			"/nuestros-productos",
			"/outlet%20outlet",
			"/listado/computacion/laptops-accesorios/notebooks",
			"/listado/computacion/pc-escritorio",
			"/p/garantia",
			"/p/sucursales",
			"/p/como-comprar",
			"/listado/computacion/pc-escritorio/pc-escritorio",
			"/p/como-cancelar-compra",
			"/p/contratos-de-adhesion",
			"/p/quienes-somos",
			"/p/drivers",
			"/p/avisos-legales",
		],
		selectors: {
			productWrapper: ".mshops-search-polycard.poly-card",
			title_raw: ".poly-component__title",
			price: ".andes-money-amount__fraction",
			product_url: ".poly-component__title",
			image_url: ".poly-component__picture",
		},
		timeout: 30000,
	}),
	//
	gezatek: new SiteConfig({
		store_name: "Gezatek",
		store_id: "gezatek",
		store_url: "https://www.gezatek.com.ar/tienda/",
		store_image: "/images/stores/gezatek.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"pc-hogar-y-oficina/",
			"pc-basic-gamer/",
			"pc-elite-gamer/",
			"pc-xtreme-gamer/",
			"notebooks/",
			"accesorios-notebook/",
			"smart-tv/",
			"combos-amd/",
			"combos-intel/",
			"procesadores-amd//",
			"procesadores-intel/",
			"mothers-amd-am4/",
			"mothers-amd-am5/",
			"mothers-intel-lga1200/",
			"mothers-intel-lga1700/",
			"mothers-intel-lga1851/",
			"ram-ddr3/",
			"ram-ddr4/",
			"ram-ddr5/",
			"ram-sodimm-ddr4/",
			"vga-nvidia/",
			"vga-amd/",
			"monitores/",
			"discos-ssd-sata3/",
			"discos-ssd-m2-nvme/",
			"discos-rigidos/",
			"discos-externos-usb/",
			"opticos/",
			"fuentes/",
			"gabinetes/",
			"gabinetes-con-fuente/",
			"gabinetes/",
			"mouse/",
			"mousepads/",
			"teclados-kit/",
			"auriculares/",
			"parlantes/",
			"webcam/",
			"gamepad-joystick/",
			"impresoras/",
			"estabilizadores/",
			"sillas/",
			"coolers-cpu/",
			"water-cooling/",
			"cooler-fan/",
			"routers-y-repetidores-wifi/",
			"placas-de-red-usb/",
			"placas-de-red-internas/",
			"switches-de-red/",
			"tabletas-digitalizadoras/",
			"micro-sd/",
			"pendrive/",
			"adaptadores/",
			"cables/",
			"insumos/",
			"streaming/",
		],
		selectors: {
			productWrapper: ".col-md-4.col-xs-6.productos.c-s",
			title_raw: "h2 .click",
			price: ".price.pull-left.precio_web",
			product_url: "a.click",
			image_url: ".figure img.img-responsive",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	goldenTech: new SiteConfig({
		store_name: "GoldenTech Store",
		store_id: "goldentech",
		store_url: "https://goldentechstore.com.ar/",
		store_image: "/images/stores/goldentech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"almacenamiento/",
			"motherboards/",
			"fuentes/",
			"placas-de-video/",
			"gabinetes/",
			"procesadores/",
			"memorias-ram/",
			"refrigeracion/",
			"pc-armadas/",
			"monitores/",
			"conectividad/",
			"perifericos/",
			"sillas-gamer/",
			"notebooks/",
			"accesorios/",
			"outlet/",
		],
		selectors: {
			productWrapper: ".product.type-product",
			title_raw: ".woocommerce-loop-product__title a",
			price: ".woocommerce-Price-amount bdi",
			product_url: ".post_image a",
			image_url: ".attachment-woocommerce_thumbnail",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	hfTecnologia: new SiteConfig({
		store_name: "HF Tecnologia",
		store_id: "hftecnologia",
		store_url: "https://hftecnologia.com.ar/",
		store_image: "/images/stores/hftecnologia.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"notebooks/",
			"pc-armadas/",
			"accesorios/",
			"componentes-de-pc/",
			"conectividad/",
			"hogar/",
			"impresoras/",
			"otros/",
			"perifericos/",
			"tabletas-graficas/",
			"perifericos/",
		],
		selectors: {
			productWrapper: ".products-list__item",
			title_raw: ".product-card__name h2",
			price: ".product-card__prices",
			product_url: ".product-card__name a",
			image_url: ".product-image__img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	arShop: new SiteConfig({
		store_name: "AR Shop",
		store_id: "arshop",
		store_url: "https://ar-shop.com.ar/",
		store_image: "/images/stores/arshop.png",
		trust_factor_manual: 70,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "argentina", "setup"],
		pages: [
			"auriculares/",
			"componentes-pc/",
			"gabinetes/",
			"consolas/",
			"monitores/",
			"parlantes-bt/",
			"perifericos/",
			"sillas-gamer/",
			"outlet/",
			"joystick-gamepad/",
			"coleccionables/",
			"computadoras-pc/",
		],
		selectors: {
			productWrapper: ".js-item-product",
			title_raw: ".js-item-name",
			price: ".js-price-display",
			product_url: ".item-link",
			image_url: ".js-item-image-padding img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	acuarioInsumos: new SiteConfig({
		store_name: "Acuario Insumos",
		store_id: "acuarioinsumos",
		store_url: "https://www.insumosacuario.com.ar/",
		store_image: "/images/stores/acuarioinsumos.png",
		trust_factor_manual: 10,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"almacenamiento/",
			"audio/",
			"computadoras/",
			"conectividad/",
			"conectores/",
			"energia/",
			"hardware/",
			"monitores/",
			"otros/",
			"outlet-/",
			"perifericos/",
			"Sillas-/",
			"soportes/",
			"conectores/",
			"hardware/",
			"hardware/",
			"hardware/",
			"hardware/",
		],
		selectors: {
			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".pecio_final.ft b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	wizTech: new SiteConfig({
		store_name: "WIZ TECH",
		store_id: "wiztech",
		store_url: "https://wiztech.com.ar/",
		store_image: "/images/stores/wiztech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["catalogo"],
		selectors: {
			productWrapper: ".product-selector",
			title_raw: ".card-title",
			price: ".card-description .ng-star-inserted",
			product_url: ".card",
			image_url: ".card-header img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	xtPc: new SiteConfig({
		store_name: "Xt-PC",
		store_id: "xtpc",
		store_url: "https://www.xt-pc.com.ar/",
		store_image: "/images/stores/xtpc.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"cat/supra/32/notebooks/",
			"tag/periferico",
			"cat/supra/18/monitores/",
			"cat/supra/3/placas-de-video/",
			"cat/supra/1/microprocesador/",
			"cat/supra/12/almacenamiento/",
			"cat/supra/4/memorias/",
			"cat/supra/2/motherboard/",
		],
		selectors: {
			productWrapper: ".item.product-list",
			title_raw: ".info h3",
			price: ".price",
			product_url: "a",
			image_url: ".image img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	empenioGamer: new SiteConfig({
		store_name: "Empeño Gamer",
		store_id: "empeniogamer",
		store_url: "https://empeniogamer.com.ar/",
		store_image: "/images/stores/empeniogamer.png",
		trust_factor_manual: 70,
		seller_type: ["setup", "componentes"],
		tags: ["gaming", "argentina", "setup"],
		pages: ["tienda"],
		selectors: {
			productWrapper: ".product.type-product",
			title_raw: ".product-name a",
			price: ".woocommerce-Price-amount bdi",
			product_url: ".product-thumb",
			image_url: ".attachment-woocommerce_thumbnail",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	hardCore: new SiteConfig({
		store_name: "HardCore",
		store_id: "hardcore",
		store_url: "https://hardcorecomputacion.com.ar/categoria-producto/",
		store_image: "/images/stores/hardcore.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"microprocesadores/",
			"perifericos/",
			"sillon-gamer/",
			"notebooks/",
			"monitores/",
			"placas-de-red/",
			"conectividad/",
			"accesorios/",
			"estabilizadores-y-ups/",
			"outlet/",
			"motherboards/",
			"memorias/",
			"gabinetes/",
			"fuentes/",
			"almacenamiento/",
			"placasdevideo/",
			"cooling/",
		],
		selectors: {
			productWrapper: ".product.type-product",
			title_raw: ".woocommerce-loop-product__title",
			price: ".woocommerce-Price-amount bdi",
			product_url: ".woocommerce-LoopProduct-link",
			image_url: ".attachment-woocommerce_thumbnail",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	hyperGaming: new SiteConfig({
		store_name: "Hyper Gaming",
		store_id: "hypergaming",
		store_url: "https://www.hypergaming.com.ar/",
		store_image: "/images/stores/hypergaming.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"monitores/",
			"motherboards/",
			"notebooks/",
			"pc-armadas/",
			"perifericos/",
			"placas-de-video/",
			"procesadores/",
			"refrigeracion/",
			"seguridad/",
			"sillas/",
			"placas-de-video/",
			"perifericos/",
			"procesadores/",
			"notebooks/",
			"monitores/",
		],
		selectors: {
			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".pecio_final.ft b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	ignaTech: new SiteConfig({
		store_name: "IgnaTech",
		store_id: "ignatech",
		store_url: "https://www.ignatech.com.ar/",
		store_image: "/images/stores/ignatech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"componentes/",
			"conectividad/",
			"consolas/",
			"estabilizadores-y-ups/",
			"monitores/",
			"notebook/",
			"pc-armadas/",
			"perifericos/",
			"seguridad/",
			"sillas-gamer/",
			"televisores/",
		],
		selectors: {
			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".pecio_final.ft b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	integradosArgentinos: new SiteConfig({
		store_name: "Integrados Argentinos",
		store_id: "integradosargentinos",
		store_url: "https://www.integradosargentinos.com/",
		store_image: "/images/stores/integradosargentinos.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"listado/computacion/pc-escritorio/pc/",
			"listado/computacion/accesorios-pc-gaming/auriculares/",
			"listado/computacion/monitores-accesorios/monitores/",
			"disco_DisplayType_G",
			"listado/consolas-videojuegos/accesorios-pc-gaming/auriculares/",
			"listado/computacion/laptops-accesorios/notebooks/",
			"listado/computacion/componentes-pc/",
			"listado/computacion/perifericos-pc/mouses-teclados/teclados/",
			"listado/computacion/perifericos-pc/mouses-teclados/mouses/",
			"listado/computacion/perifericos-pc/mouses-teclados/mouse-pads/",
			"listado/computacion/perifericos-pc/webcams/",
			"listado/computacion/perifericos-pc/mouses-teclados/kits-mouse-teclado/",
			"listado/computacion/accesorios-pc-gaming/auriculares/",
			"listado/computacion/accesorios-pc-gaming/microfonos/",
		],
		selectors: {
			productWrapper: ".ui-search-result__wrapper",
			title_raw: ".poly-component__title",
			price: ".andes-money-amount__fraction",
			product_url: ".poly-component__title",
			image_url: ".poly-component__picture",
		},
		timeout: 30000,
	}),
	//
	katech: new SiteConfig({
		store_name: "Katech",
		store_id: "katech",
		store_url: "https://katech.com.ar/",
		store_image: "/images/stores/katech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"/categoria/procesadores/",
			"/categoria/procesadores/microprocesadores-am4/",
			"/categoria/microprocesadores-am5-procesadores/",
			"/categoria/placas-de-video/",
			"/categoria/refrigeracion-pc/",
			"/categoria/water-cooler-refrigeracion-cpu/",
			"/categoria/refrigeracion-gabinete/",
			"/categoria/motherboards/",
			"/categoria/motherboard-amd-am4/",
			"/categoria/motherboard-amd-am5/",
			"/categoria/motherboard-amd-fm2/",
			"/categoria/motherboard-lga-1851/",
			"/categoria/motherboards/motherboard-lga-1700/",
			"/categoria/motherboards/motherboard-lga-1200/",
			"/categoria/motherboards/motherboard-lga-1151/",
			"/categoria/memorias-ram/",
			"/categoria/memorias/memoria-ram-ddr3/",
			"/categoria/memorias/memoria-ram-ddr4/",
			"/categoria/memorias/memoria-ram-ddr5/",
			"/categoria/memorias/memoria-ram-sodimm-ddr3/",
			"/categoria/memorias/memoria-ram-sodimm-ddr4/",
			"/categoria/almacenamiento/",
			"/categoria/disco-duro-hdd-2-5-notebook/",
			"/categoria/disco-duro-hdd-3-5-sata/",
			"/categoria/ssd-almacenamiento/",
			"/categoria/ssd-m2-almacenamiento/",
			"/categoria/disco-duro-hdd-nas/",
			"/categoria/gabinetes/",
			"/categoria/gabinete-gamer-gabinetes/",
			"/categoria/gabinete-kit-gabinetes/",
			"/categoria/fuentes/",
			"/categoria/fuentes-80-plus/",
			"/categoria/fuentes-genericas/",
			"/categoria/pc-gamer/",
			"/pc-armadas/",
			"/categoria/powered-by-corsair/",
			"/categoria/mini-pc-pc-armadas/",
			"/categoria/servidores/",
			"/categoria/notebooks/",
			"/categoria/notebooks/notebooks-gamer/",
			"/categoria/notebooks/notebooks-oficina/",
			"/categoria/gameroom/",
			"/categoria/gameroom/capturadoras-y-streaming/",
			"/categoria/consolas/",
			"/categoria/consolas-de-juego-consolas/",
			"/categoria/juegos-consola-consolas/",
			"/categoria/controladoras-y-rgb-gameroom/",
			"/categoria/gameroom/escritorio-pc/",
			"/categoria/gameroom/sillas-gamers/",
			"/categoria/gameroom/smart-home/",
			"/categoria/gameroom/televisores/",
			"/categoria/monitores/",
			"/categoria/monitores/monitores-diseno/",
			"/categoria/monitores/monitores-gamer/",
			"/categoria/monitores/monitores-oficina/",
			"/categoria/apple/",
			"/categoria/iphone-apple/",
			"/categoria/ipad-apple/",
			"/categoria/macbook-apple/",
			"/categoria/mouse/",
			"/categoria/mouse/mouse-gamer/",
			"/categoria/mouse/mouse-oficina/",
			"/categoria/mouse/mouse-inalambrico/",
			"/categoria/mouse-pad/",
			"/categoria/teclados/",
			"/categoria/teclados/teclados-gamer/",
			"/categoria/teclados/teclados-inalambrico/",
			"/categoria/teclados/teclado-gamer-inalambrico/",
			"/categoria/teclados/teclados-y-mouse-teclados",
			"/categoria/auriculares-y-microfonos/",
			"/categoria/auriculares-bluetooth/",
			"/categoria/parlantes/",
			"/categoria/camaras/",
			"/categoria/camaras/camaras-digitales-camaras",
			"/categoria/camaras/go-pro-camaras",
			"/categoria/camaras/webcams-camaras",
			"/categoria/volantes/",
			"/categoria/volantes-y-pedales/",
			"/categoria/accesorios/",
			"/categoria/accesorios-apple/",
			"/categoria/almacenamiento-externo/",
			"/categoria/almacenamiento-externo/hdd-externos/",
			"/categoria/pen-drives/",
			"/categoria/accesorios/cables-accesorios",
			"/categoria/power-banks-y-cargadores/",
			"/categoria/soportes-accesorios/",
			"/categoria/tableta-digitalizadora/",
			"/categoria/bluetooth/",
			"/categoria/estabilizadores-y-ups/",
			"/categoria/conectividad-y-redes/",
			"/categoria/wifi-pcie-conectividad-y-redes/",
			"/categoria/cpe-conectividad-y-redes/",
			"/categoria/router-wireless-conectividad-y-redes/",
			"/categoria/wifi-usb-conectividad-y-redes/",
			"/categoria/motherboard-lga-1200/",
			"/categoria/monitores-diseno/",
			"/tipo-de-pc/pc-gamer-placa-de-video/",
			"/tipo-de-pc/pc-gamer-video-integrado/",
			"/tipo-de-pc/pc-gamer-intel/",
			"/categoria/sillas-gamers/",
			"/producto/video-geforce-rtx-5070-12gb-asus-prime/",
			"/producto/monitor-gamer-aoc-24g42e-24-180-hz/",
			"/producto/monitor-gamer-24-aoc-ag246fk-540-hz/",
			"/wp-content/uploads/x1-1436-215x215.avif",
			"/producto/silla-gamer-raptor-throne-s10-black/",
			"/producto/silla-gamer-xpg-nexus-negro/",
			"/wp-content/uploads/x1-1389-215x215.avif",
			"/producto/silla-gamer-corsair-tc500-luxe-frost/",
			"/wp-content/uploads/x1-1461-215x215.avif",
			"/producto/silla-gamer-razer-iskur-x/",
			"/producto/pasta-termica-mx-6-4grs/",
			"/producto/procesador-amd-ryzen-5-5600gt-am4/",
			"/producto/disco-ssd-1tb-kingston-nv3-nvme/",
			"/producto/procesador-amd-ryzen-5-9600x-am5/",
			"/wp-content/uploads/x2-474-215x215.avif",
			"/producto/fuente-asus-rog-strix-1000w-platinum/",
			"/producto/fuente-asus-rog-strix-1200w-platinum/",
			"/producto/fuente-asus-tuf-gaming-1000w-gold/",
			"/producto/mouse-logitech-wir-m650-graphite/",
			"/producto/mouse-logitech-g305-wireless-white/",
			"/producto/mouse-logitech-g-pro-x-superlight-red/",
			"/producto/tl-sf1024d-switch-24p-tp-link-desktop/",
			"/producto/monitor-philips-22-221v8l-77-vga-hdmi/",
			"/marca/corsair/",
			"/marca/gigabyte/",
			"/marca/logitech/",
			"/marca/asus/",
			"/marca/coolermaster/",
			"/marca/thermaltake/",
			"/marca/msi/",
			"/marca/amd/",
			"/marca/razer/",
			"/marca/tp-link/",
			"/marca/adata/",
			"/marca/kingston/",
			"/marca/trust/",
			"/marca/genius/",
			"/marca/lenovo/",
			"/marca/western-digital/",
			"/marca/aerocool/",
			"/marca/patriot/",
			"/marca/evga/",
			"/marca/apple/",
			"/marca/samsung/",
			"/marca/crucial/",
			"/marca/seagate/",
			"/marca/aorus/",
			"/marca/benq/",
			"/marca/elgato/",
			"/marca/jbl/",
			"/marca/netac/",
			"/marca/evolabs/",
			"/marca/noblex/",
			"/marca/acer/",
			"/marca/microsoft/",
			"/marca/redragon/",
			"/marca/toshiba/",
			"/marca/gskill/",
			"/hardware/",
			"/producto/teclado-logitech-g515-tkl-negro/",
			"/producto/auricular-hyperx-cloud-iii-blanco-rosa/",
			"https://api.whatsapp.com/send",
			"/wallpapers/",
			"/informar-pago/",
			"/katech-para-empresas/",
			"/garantia/",
			"/libro-de-quejas-on-line/",
			"/seguimiento-de-pedidos/",
			"/term-conditions/",
			"/categoria/notebooks-gamer/",
			"/categoria/notebooks-oficina/",
			"/categoria/capturadoras-y-streaming/",
			"/categoria/escritorio-pc/",
			"/categoria/smart-home/",
			"/categoria/televisores/",
			"/categoria/monitores-gamer/",
			"/categoria/monitores-oficina/",
			"/categoria/cables-accesorios/",
		],
		selectors: {
			productWrapper: ".w-grid-item.product.type-product",
			title_raw: ".post_title a",
			price: ".woocommerce-Price-amount.amount bdi",
			product_url: ".post_title a",
			image_url: ".wp-post-image",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	liontech: new SiteConfig({
		store_name: "Liontech Gaming",
		store_id: "liontech",
		store_url: "https://www.liontech-gaming.com/",
		store_image: "/images/stores/liontech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"product-category/componentes-de-pc/",
			"product-category/perifericos/",
			"product-category/conectividad/",
			"product-category/almacenamiento/",
			"product-category/combo-actualizacion/",
			"ofertas/",
			"product-category/pc-armada/",
			"product-category/notebooks/",
			"product-category/tablet/",
			"product-category/outlet/",
			"product-category/monitores/",
			"product-category/consolas/",
			"product-category/pc-armada/",
		],
		selectors: {
			productWrapper: ".product-inner",
			title_raw: ".woocommerce-loop-product__title",
			price: ".woocommerce-Price-amount.amount bdi",
			product_url: ".product-loop-title",
			image_url: ".wp-post-image",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	malditoHard: new SiteConfig({
		store_name: "Maldito Hard",
		store_id: "malditohard",
		store_url: "https://www.malditohard.com.ar/",
		store_image: "/images/stores/malditohard.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"categoria/pc-gamer/",
			"categoria/pcs-armadas/",
			"categoria/sillas-gamer/",
			"categoria/monitores/",
			"categoria/placa-de-video/",
			"categoria/notebooks/",
			"hardware/",
			"categoria/accesorios/",
			"categoria/tecnologia/",
			"/hardware/?filter_product_cat=auriculares,mouses,parlantes,teclados",
		],
		selectors: {
			productWrapper: ".w-grid-item.product.type-product",
			title_raw: ".woocommerce-loop-product__title a",
			price: ".woocommerce-Price-amount.amount bdi",
			product_url: ".post_image a",
			image_url: ".wp-post-image",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	maxTecno: new SiteConfig({
		store_name: "Max Tecno",
		store_id: "maxtecno",
		store_url: "https://maxtecno.com.ar/",
		store_image: "/images/stores/maxtecno.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"equipos-armados/",
			"monitores/",
			"notebooks/",
			"impresoras/",
			"seguridad/",
			"ofertas/",
			"categoria/perifericos/teclados-perifericos/",
			"categoria/perifericos/parlantes-periféricos/",
			"categoria/perifericos/joystick-periféricos/",
			"categoria/perifericos/auriculares-periféricos/",
			"categoria/perifericos/mouse-pad-periféricos/",
			"categoria/perifericos/mouse-perifericos/",
			"categoria/perifericos/volantes-periféricos/",
			"categoria/sillas/sillas-gamer-sillas/",
			"categoria/estbilizador/estabilizador-de-tension-estbilizador/",
		],
		selectors: {
			productWrapper: ".w-grid-item.product.type-product",
			title_raw: ".woocommerce-loop-product__title a",
			price: ".woocommerce-Price-amount.amount bdi",
			product_url: ".post_image a",
			image_url: ".attachment-woocommerce_thumbnail",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	megasoft: new SiteConfig({
		store_name: "Megasoft",
		store_id: "megasoft",
		store_url: "https://www.megasoftargentina.com.ar/",
		store_image: "/images/stores/megasoft.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"accesorios---cables/",
			"Auriculares---Microfonos/",
			"Combo-Actualizacion/",
			"Conectividad_2/",
			"consolas/",
			"Coolers---Watercooling/",
			"Fuentes---Ups---Estabilizadores/",
			"Gabinetes_2/",
			"Impresoras---Insumos/",
			"Joystick/",
			"Memorias-Ram-/",
			"Mini-Pc/",
			"Monitores/",
			"Motherboards/",
			"Notebooks/",
			"Parlantes---Audio/",
			"Pc-Armadas_2/",
			"Pendrives---Micro-Sd/",
			"Perifericos-Pc/",
			"Placas-De-Sonido/",
			"Placas-De-Video/",
			"Procesadores/",
			"rigidos---solidos/",
			"sillas-y-mesa-gamer/",
			"soporte-tecnico/",
			"Soportes/",
			"streaming-media-player/",
			"super-ofertas/",
			"televisores/",
		],
		selectors: {
			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".pecio_final.ft b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	mexx: new SiteConfig({
		store_name: "Mexx",
		store_id: "mexx",
		store_url: "https://www.mexx.com.ar/productos-rubro/",
		store_image: "/images/stores/mexx.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"tablets/",
			"notebooks/",
			"motherboards/",
			"procesadores/",
			"memorias-ram/",
			"almacenamiento/",
			"placas-de-video/",
			"fuentes-de-poder/",
			"gabinetes/",
			"refrigeracion-pc/",
			"gabinetes/",
			"combos-actualizacion-pc/",
			"teclados,-mouses-y-pads/",
			"auriculares-y-microfonos-/",
			"camaras-web-e-ip/",
			"streaming-/",
			"monitores/",
			"conectividad-y-redes/",
			"ups-y-estabilizadores/",
			"sillas-y-escritorios-gamers-/",
			"consolas-/",
			"volantes-y-gamepads/",
			"parlantes-y-audio/",
			"proyectores-/",
			"tabletas-graficas/",
			"tv-/",
			"cables/",
			"outlet/",
		],
		selectors: {
			productWrapper: ".productos.col-md-4.pull-left",
			title_raw: ".card-title a",
			price: ".card-footer b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20 img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	noxieStore: new SiteConfig({
		store_name: "Noxie Store",
		store_id: "noxiestore",
		store_url: "https://www.noxiestore.com/",
		store_image: "/images/stores/noxiestore.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: [
			"teclados-y-mouses/",
			"almacenamiento/",
			"audio/",
			"cables-y-adaptadores/",
			"combo-actualizacion/",
			"conectividad-y-redes/",
			"gabinetes/",
			"gamepad---joystick/",
			"memorias-ram/",
			"monitores-y-televisores/",
			"mother/",
			"pc-armadas/",
			"placas-de-video/",
			"procesadores/",
			"refrigeracion/",
			"sillas-gamers/",
		],
		selectors: {
			productWrapper: ".col-md-3.listado-.pull-left.prod-cat",
			title_raw: ".card-title a",
			price: ".pecio_final.ft b",
			product_url: ".card-title a",
			image_url: ".view.overlay.px-20.imagen img",
		},
		timeout: 30000,
	}),
	// ! WITHOUT SELECTORS
	// ! WITHOUT NEW PATHS
	peakComputacion: new SiteConfig({
		store_name: "Peak Computacion",
		store_id: "peakcomputacion",
		store_url: "https://www.peakcomputacion.com.ar",
		store_image: "/images/stores/peakcomputacion.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	rocketHard: new SiteConfig({
		store_name: "Rocket Hard",
		store_id: "rockethard",
		store_url: "https://www.rockethard.com.ar",
		store_image: "/images/stores/rockethard.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	scpHardstore: new SiteConfig({
		store_name: "SCP Hardstore",
		store_id: "scphardstore",
		store_url: "https://www.scphardstore.com.ar",
		store_image: "/images/stores/scphardstore.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	shopGamer: new SiteConfig({
		store_name: "ShopGamer",
		store_id: "shopgamer",
		store_url: "https://www.shopgamer.com.ar",
		store_image: "/images/stores/shopgamer.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	space: new SiteConfig({
		store_name: "Space",
		store_id: "space",
		store_url: "https://www.space.com.ar",
		store_image: "/images/stores/space.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	theGamerShop: new SiteConfig({
		store_name: "The Gamer Shop",
		store_id: "thegamershop",
		store_url: "https://www.thegamershop.com.ar",
		store_image: "/images/stores/thegamershop.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	tiendaTrade: new SiteConfig({
		store_name: "Tiendatrade",
		store_id: "tiendatrade",
		store_url: "https://www.tiendatrade.com.ar",
		store_image: "/images/stores/tiendatrade.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	turtech: new SiteConfig({
		store_name: "Turtech",
		store_id: "turtech",
		store_url: "https://www.turtech.com.ar",
		store_image: "/images/stores/turtech.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	// ! WITHOUT NEW PATHS
	uranoStream: new SiteConfig({
		store_name: "Urano Stream",
		store_id: "uranostream",
		store_url: "https://www.uranostream.com.ar",
		store_image: "/images/stores/uranostream.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	gorilaGames: new SiteConfig({
		store_name: "Urano Stream",
		store_id: "gorilagames",
		store_url: "https://www.uranostream.com.ar",
		store_image: "/images/stores/uranostream.png",
		trust_factor_manual: 70,
		seller_type: ["componentes"],
		tags: ["gaming", "argentina", "componentes"],
		pages: ["/productos"],
		selectors: {
			productWrapper: "",
			title_raw: "",
			price: "",
			product_url: "",
			image_url: "",
		},
		timeout: 30000,
	}),
	//
	//
};